version: '3'

services:
  cheese.web:
    image: cheese.web
    build:
      context: .
      dockerfile: Cheese.Web/Dockerfile

  identityserverwithaspnetidentity:
    image: identityserverwithaspnetidentity
    build:
      context: .
      dockerfile: IdentityServerWithAspNetIdentity/Dockerfile

